### ISSUE TITLE
Support additional site: Slack

### ISSUE THREAD

**Issue by timhillgit** [zchr/zoomies#10]
I've got a branch for this but it doesn't work at the moment: https://github.com/zchr/zoomies/compare/main...timhillgit:zoomies:slack

It looks like `changeInfo.status` is always coming back as `loading`.

**Comment by zchr** [comment]
Thanks for getting started on this! I’ll checkout your branch and check out the `changeInfo` in the morning (EST).

**Comment by zchr** [comment]
@timhillgit I'm seeing the same thing. Let's remove the `changeInfo` condition for now. Since we assert the tab is active, that ought to be enough.
