### ISSUE TITLE
Support additional sites: Linear, Miro, Around

### ISSUE THREAD

**Issue by zchr** [zchr/zoomies#2]
https://news.ycombinator.com/item?id=34545844

**Comment by zchr** [comment]
Implemented--will be out in v0.6.0

**Comment by HerrNiklasRaab** [comment]
Hey, just found your extension. This is a live saver! Is this already out? Can't see it:

<img width="290" alt="CleanShot 2023-01-31 at 18 47 12@2x" src="https://user-images.githubusercontent.com/28401593/215841709-a7f8ebba-81fe-4868-9696-7a08cfd2d5d2.png">
